export const SEND_MESSAGE_REQUEST_START = 'SEND_MESSAGE_REQUEST_START';
export const SEND_MESSAGE_REQUEST_SUCCESS = 'SEND_MESSAGE_REQUEST_SUCCESS';
export const SEND_MESSAGE_REQUEST_FAIL = 'SEND_MESSAGE_REQUEST_FAIL';

export const RECEIVE_MESSAGE_SUCCESS = 'RECEIVE_MESSAGE_SUCCESS';

export const LIST_FRIEND_MESSAGES_REQUEST_START = 'LIST_FRIEND_MESSAGES_REQUEST_START';
export const LIST_FRIEND_MESSAGES_REQUEST_SUCCESS = 'LIST_FRIEND_MESSAGES_REQUEST_SUCCESS';
export const LIST_FRIEND_MESSAGES_REQUEST_FAIL = 'LIST_FRIEND_MESSAGES_REQUEST_FAIL';

export const LIST_GROUP_MESSAGES_REQUEST_START = 'LIST_GROUP_MESSAGES_REQUEST_START';
export const LIST_GROUP_MESSAGES_REQUEST_SUCCESS = 'LIST_GROUP_MESSAGES_REQUEST_SUCCESS';
export const LIST_GROUP_MESSAGES_REQUEST_FAIL = 'LIST_GROUP_MESSAGES_REQUEST_FAIL';