export const LIST_FRIENDS_REQUEST_START = 'LIST_FRIENDS_REQUEST_START';
export const LIST_FRIENDS_REQUEST_SUCCESS = 'LIST_FRIENDS_REQUEST_SUCCESS';
export const LIST_FRIENDS_REQUEST_FAIL = 'LIST_FRIENDS_REQUEST_FAIL';

export const ADD_FRIEND_REQUEST_START = 'ADD_FRIEND_REQUEST_START';
export const ADD_FRIEND_REQUEST_SUCCESS = 'ADD_FRIEND_REQUEST_SUCCESS';
export const ADD_FRIEND_REQUEST_FAIL = 'ADD_FRIEND_REQUEST_FAIL';

export const LIST_GROUPS_REQUEST_START = 'LIST_GROUPS_REQUEST_START';
export const LIST_GROUPS_REQUEST_SUCCESS = 'LIST_GROUPS_REQUEST_SUCCESS';
export const LIST_GROUPS_REQUEST_FAIL = 'LIST_GROUPS_REQUEST_FAIL';

export const ADD_GROUP_REQUEST_START = 'ADD_GROUP_REQUEST_START';
export const ADD_GROUP_REQUEST_SUCCESS = 'ADD_GROUP_REQUEST_SUCCESS';
export const ADD_GROUP_REQUEST_FAIL = 'ADD_GROUP_REQUEST_FAIL';

export const SET_ATTRIBUTE_REQUEST_START = 'SET_ATTRIBUTE_REQUEST_START';
export const SET_ATTRIBUTE_REQUEST_SUCCESS = 'SET_ATTRIBUTE_REQUEST_SUCCESS';
export const SET_ATTRIBUTE_REQUEST_FAIL = 'SET_ATTRIBUTE_REQUEST_FAIL';