export const LIST_FRIENDS_REQUEST_START = 'LIST_FRIENDS_REQUEST_START';
export const LIST_FRIENDS_REQUEST_SUCCESS = 'LIST_FRIENDS_REQUEST_SUCCESS';
export const LIST_FRIENDS_REQUEST_FAIL = 'LIST_FRIENDS_REQUEST_FAIL';

export const LIST_GROUP_MESSAGES_REQUEST_START = 'LIST_GROUP_MESSAGES_REQUEST_START';
export const LIST_GROUP_MESSAGES_REQUEST_SUCCESS = 'LIST_GROUP_MESSAGES_REQUEST_SUCCESS';
export const LIST_GROUP_MESSAGES_REQUEST_FAIL = 'LIST_GROUP_MESSAGES_REQUEST_FAIL';

export const RECENT_FRIENDS_MESSAGES_REQUEST_START = 'RECENT_FRIENDS_MESSAGES_REQUEST_START';
export const RECENT_FRIENDS_MESSAGES_REQUEST_SUCCESS = 'RECENT_FRIENDS_MESSAGES_REQUEST_SUCCESS';
export const RECENT_FRIENDS_MESSAGES_REQUEST_FAIL = 'RECENT_FRIENDS_MESSAGES_REQUEST_FAIL';

export const RECENT_GROUPS_MESSAGES_REQUEST_START = 'RECENT_GROUPS_MESSAGES_REQUEST_START';
export const RECENT_GROUPS_MESSAGES_REQUEST_SUCCESS = 'RECENT_GROUPS_MESSAGES_REQUEST_SUCCESS';
export const RECENT_GROUPS_MESSAGES_REQUEST_FAIL = 'RECENT_GROUPS_MESSAGES_REQUEST_FAIL';